"use client"

import { useMemo, useState } from "react"
import { searchCourses } from "@/domain/search"
import type { Catalog, WorkspaceState } from "@/domain/types"

export const ExplorePage = ({ workspace, catalog, onCommand }: { workspace: WorkspaceState, catalog: Catalog, onCommand: (command: Record<string, unknown>) => void }) => {
  const [query, setQuery] = useState("")
  const [subject, setSubject] = useState("All")
  const [noFriday, setNoFriday] = useState(workspace.profile.excludedDays.includes("fri"))
  const [afterEarliest, setAfterEarliest] = useState(true)
  const [countsForCs, setCountsForCs] = useState(false)
  const [filtersOpen, setFiltersOpen] = useState(false)
  const subjects = useMemo(() => [...new Set(catalog.courses.map((course) => course.subject))].sort(), [catalog.courses])
  const plan = workspace.plans[0]
  const scenario = plan.scenarios.find((item) => item.id === plan.activeScenarioId) ?? plan.scenarios[0]
  const plannedIds = new Set(scenario.courses.map((item) => item.courseId))
  const results = useMemo(() => searchCourses(catalog, { query, termId: workspace.currentTermId, subjects: countsForCs ? ["CS"] : subject === "All" ? undefined : [subject], excludedDays: noFriday ? ["fri"] : undefined, earliestStart: afterEarliest ? workspace.profile.earliestStart : undefined }).slice(0, 12), [afterEarliest, catalog, noFriday, query, subject, countsForCs, workspace.currentTermId, workspace.profile.earliestStart])
  const add = (courseId: string, sectionId: string | undefined, units: number, code: string) => onCommand({ type: "edit_plan", planId: plan.id, scenarioId: scenario.id, operations: [{ type: "add_course", planCourse: { id: `PLANCOURSE-${code.replaceAll(" ", "-")}-${crypto.randomUUID().slice(0, 8).toUpperCase()}`, courseId, sectionId: sectionId ?? null, units, status: "active" } }] })
  return <div className="page explore-page explore-rebuild"><header className="page-heading"><div><p className="eyebrow">Stanford reference</p><h1>Browse courses</h1><p>Start from the catalog. CourseContext keeps course identity separate from term-specific meeting information.</p></div><a className="secondary-button" href="https://bulletin.stanford.edu/" target="_blank" rel="noreferrer">Open Stanford Bulletin ↗</a></header>
    <aside className="reference-notice"><span>i</span><p><strong>Shared reference, not a personal choice</strong><small>Courses appear in your plan only after you add them. Meeting data in this challenge build is a planning sample and must be verified before enrollment.</small></p></aside>
    <section className="explore-search"><label><span aria-hidden="true">⌕</span><input aria-label="Search courses" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Course code, topic, or keyword" /></label><select aria-label="Subject" value={subject} onChange={(event) => setSubject(event.target.value)} disabled={countsForCs}><option>All</option>{subjects.map((item) => <option key={item}>{item}</option>)}</select><button className="filter-button" aria-expanded={filtersOpen} onClick={() => setFiltersOpen((value) => !value)}>Filters <span>{[noFriday, afterEarliest, countsForCs].filter(Boolean).length}</span></button></section>
    <div className={`explore-body ${filtersOpen ? "filters-open" : ""}`}><aside className="filter-rail"><p className="nav-label">Planning filters</p><label><input type="checkbox" checked={noFriday} onChange={(event) => setNoFriday(event.target.checked)} /> No Friday meetings</label><label><input type="checkbox" checked={afterEarliest} onChange={(event) => setAfterEarliest(event.target.checked)} /> Starts after {workspace.profile.earliestStart}</label><label><input type="checkbox" checked={countsForCs} onChange={(event) => setCountsForCs(event.target.checked)} /> CS subject only</label><button className="text-button" type="button" onClick={() => { setNoFriday(false); setAfterEarliest(false); setCountsForCs(false); setSubject("All") }}>Clear filters</button><div className="source-status"><span>i</span><p><b>Catalog reference</b><small>Stanford 2026-27 sources</small></p></div></aside><section className="result-section"><div className="section-heading"><div><h2>{query ? "Matching courses" : "Courses to explore"}</h2><span className="count-badge">{results.length}</span></div><span className="muted">Best match</span></div>{results.length === 0 ? <div className="library-empty"><span>⌕</span><h3>No courses match every filter</h3><p>Remove a constraint or search a broader topic.</p><button className="secondary-button" onClick={() => { setNoFriday(false); setAfterEarliest(false); setCountsForCs(false); setSubject("All") }}>Clear filters</button></div> : <div className="result-list">{results.map(({ course, sections }) => { const added = plannedIds.has(course.id); return <article className="course-result" key={course.id}><div className="result-code"><span>{course.subject}</span><strong>{course.code.replace(`${course.subject} `, "")}</strong></div><div className="result-main"><div><h3>{course.code} · {course.title}</h3><p>{course.description}</p></div><div className="tag-row">{course.tags.slice(0, 3).map((tag) => <span key={tag}>{tag}</span>)}</div><dl><div><dt>Units</dt><dd>{course.minUnits}</dd></div><div><dt>Planning sections</dt><dd>{sections.length || "Not stored"}</dd></div><div><dt>Meeting</dt><dd>{sections[0] ? `${sections[0].meetings[0].days.join("/")} ${sections[0].meetings[0].start}` : "Verify current term"}</dd></div></dl></div><div className="result-action"><span className={sections.length ? "evidence-current" : "evidence-gap"}>{sections.length ? "Planning sample" : "Offering unknown"}</span><button className={added ? "secondary-button small" : "primary-button small"} type="button" disabled={added} onClick={() => add(course.id, sections[0]?.id, course.maxUnits, course.code)} aria-label={`${added ? "Added" : "Add"} ${course.code} to plan`}>{added ? "Added" : sections.length ? "Add to plan" : "Add and verify"}</button>{course.sourceUrl && <a href={course.sourceUrl} target="_blank" rel="noreferrer">Official source ↗</a>}</div></article> })}</div>}</section></div>
  </div>
}
