"use client"

import { checkPlan } from "@/domain/planner"
import { useState } from "react"
import type { Catalog, WorkspaceState } from "@/domain/types"

const days = ["mon", "tue", "wed", "thu", "fri"] as const
const colors = ["red", "blue", "gold", "green", "slate"]

export const PlanPage = ({ workspace, catalog, onCommand }: { workspace: WorkspaceState, catalog: Catalog, onCommand: (command: Record<string, unknown>) => void }) => {
  const plan = workspace.plans[0]
  const [selectedScenarioId, setSelectedScenarioId] = useState(plan.activeScenarioId)
  const [comparisonOpen, setComparisonOpen] = useState(false)
  const [agentHelpOpen, setAgentHelpOpen] = useState(false)
  const [reportOpen, setReportOpen] = useState(false)
  const [calendarMode, setCalendarMode] = useState<"week" | "list">("week")
  const scenario = plan.scenarios.find((item) => item.id === selectedScenarioId) ?? plan.scenarios[0]
  const active = scenario.courses.filter((item) => item.status === "active")
  const backups = scenario.courses.filter((item) => item.status === "backup")
  const units = active.reduce((sum, item) => sum + item.units, 0)
  const checks = checkPlan({ scenario, catalog, profile: workspace.profile, evidence: workspace.evidence, now: new Date("2026-08-27T12:00:00Z") })
  const course = (id: string) => catalog.courses.find((item) => item.id === id)!
  const section = (id: string | null) => catalog.sections.find((item) => item.id === id)
  const remove = (id: string) => onCommand({ type: "edit_plan", planId: plan.id, scenarioId: scenario.id, operations: [{ type: "remove_course", planCourseId: id }] })
  const addScenario = () => {
    const id = `SCENARIO-OPTION-${plan.scenarios.length + 1}`
    onCommand({ type: "edit_plan", planId: plan.id, scenarioId: scenario.id, operations: [{ type: "create_scenario", scenario: { id, name: `Option ${plan.scenarios.length + 1}`, unitLimit: scenario.unitLimit, courses: scenario.courses.map((item) => ({ ...item, id: `${item.id}-${plan.scenarios.length + 1}` })), commitments: scenario.commitments.map((item) => ({ ...item, id: `${item.id}-${plan.scenarios.length + 1}` })) } }] })
  }
  return <div className="page plan-page">
    <header className="page-heading"><div><p className="eyebrow">Plan · Autumn 2026</p><h1>{plan.title}</h1><p>Build a realistic quarter around requirements, preferences, and the rest of your life.</p></div><div className="heading-actions"><button className="secondary-button" type="button" onClick={() => setComparisonOpen(true)}>Compare scenarios</button><button className="primary-button" type="button" onClick={() => setAgentHelpOpen(true)}>Ask agent to refine</button></div></header>
    <div className="scenario-tabs" role="tablist" aria-label="Plan scenarios">{plan.scenarios.map((item) => <button key={item.id} role="tab" aria-selected={scenario.id === item.id} onClick={() => setSelectedScenarioId(item.id)}>{item.name} <span>{item.id === plan.activeScenarioId ? "Current" : "Alternative"}</span></button>)}<button className="add-tab" aria-label="Add scenario" onClick={addScenario}>+</button></div>
    <div className="plan-layout">
      <section className="plan-course-panel" aria-label="Selected courses"><div className="section-heading"><div><h2>Courses</h2><span className="count-badge">{active.length}</span></div><strong>{units} units</strong></div>
        <div className="course-stack">{active.map((item, index) => { const found = course(item.courseId); const selected = section(item.sectionId); return <article className="plan-course-card" key={item.id}><i className={`course-color ${colors[index % colors.length]}`} /><div className="course-main"><div className="course-title"><span><b>{found.code}</b><small>{found.title}</small></span><span className="unit-pill">{item.units} units</span></div><p>{selected ? `${selected.meetings.map((meeting) => meeting.days.map((day) => day[0].toUpperCase()).join("")).join(" · ")} · ${selected.meetings[0]?.start}–${selected.meetings[0]?.end}` : "Section needed"}</p><p className="muted">{selected?.instructor ?? "Instructor to be announced"}</p></div><button className="more-button" type="button" onClick={() => remove(item.id)} aria-label={`Remove ${found.title}`}>×</button></article> })}</div>
        <a className="add-course-button" href="/app/explore">+ Add course</a>
        <div className="subsection"><div className="section-heading"><div><h2>Backups</h2><span className="count-badge">{backups.length}</span></div></div>{backups.map((item) => <div className="compact-row" key={item.id}><i className="course-color slate"/><span><b>{course(item.courseId).code}</b><small>{course(item.courseId).title}</small></span><em>{item.units} units</em></div>)}</div>
        <div className="subsection"><div className="section-heading"><div><h2>Commitments</h2><span className="count-badge">{scenario.commitments.length}</span></div></div>{scenario.commitments.map((item) => <div className="compact-row commitment" key={item.id}><span className="commitment-icon">◇</span><span><b>{item.title}</b><small>{item.meetings[0].days.join(", ")} · {item.meetings[0].start}–{item.meetings[0].end}</small></span></div>)}</div>
      </section>
      <section className={`calendar-panel ${calendarMode === "list" ? "list-mode" : ""}`}><div className="section-heading"><div><h2>Weekly calendar</h2><span className="week-note">Pacific time</span></div><div className="calendar-toggle"><button className={calendarMode === "week" ? "active" : ""} aria-pressed={calendarMode === "week"} onClick={() => setCalendarMode("week")}>Week</button><button className={calendarMode === "list" ? "active" : ""} aria-pressed={calendarMode === "list"} onClick={() => setCalendarMode("list")}>List</button></div></div>
        <div className="weekly-calendar" aria-label="Weekly calendar"><div className="time-column"><span />{[8, 10, 12, 14, 16, 18].map((hour) => <time key={hour}>{hour > 12 ? hour - 12 : hour} {hour >= 12 ? "PM" : "AM"}</time>)}</div>{days.map((day) => <div className="calendar-day" key={day}><b>{day.toUpperCase()}</b><div className="day-grid">{active.flatMap((item, index) => { const foundSection = section(item.sectionId); const foundCourse = course(item.courseId); return foundSection?.meetings.filter((meeting) => meeting.days.includes(day)).map((meeting) => { const start = Number(meeting.start.split(":")[0]) + Number(meeting.start.split(":")[1]) / 60; const end = Number(meeting.end.split(":")[0]) + Number(meeting.end.split(":")[1]) / 60; return <div key={`${item.id}-${day}`} className={`calendar-event ${colors[index % colors.length]}`} style={{ top: `${(start - 8) * 48}px`, height: `${Math.max((end - start) * 48, 32)}px` }}><b>{foundCourse.code}</b><span>{meeting.start}</span></div> }) ?? []})}</div></div>)}</div>
        <ul className="schedule-list" aria-label="Schedule list">{active.flatMap((item) => section(item.sectionId)?.meetings.map((meeting) => <li key={`${item.id}-${meeting.start}`}><b>{course(item.courseId).code}</b><span>{meeting.days.join(", ")} · {meeting.start}–{meeting.end}</span></li>) ?? [])}</ul>
      </section>
      <aside className="checks-panel"><div className="section-heading"><div><h2>Plan checks</h2><span className={checks.some((item) => item.severity === "error") ? "check-state warning" : "check-state clear"}>{checks.length ? checks.length : "All clear"}</span></div></div>
        {checks.length === 0 ? <div className="all-clear"><span>✓</span><strong>No hard conflicts</strong><p>Units, meeting times, outside obligations, and personal constraints all check out.</p></div> : <ul className="checks-list">{checks.map((item) => <li key={item.id}><span>!</span><div><b>{item.message}</b><p>{item.suggestedRepairs[0]}</p></div></li>)}</ul>}
        <div className="inspector-card"><p className="eyebrow">Inspector</p><h3>{scenario.name}</h3><dl><div><dt>Unit load</dt><dd>{units} / {scenario.unitLimit}</dd></div><div><dt>Friday</dt><dd>Protected</dd></div><div><dt>Evidence</dt><dd>Current</dd></div><div><dt>Last checked</dt><dd>Now</dd></div></dl><button className="text-button" type="button" onClick={() => setReportOpen(true)}>View complete check report</button></div>
      </aside>
    </div>
    {comparisonOpen && <div className="modal-backdrop" role="presentation" onMouseDown={() => setComparisonOpen(false)}><section className="scenario-comparison" role="dialog" aria-modal="true" aria-labelledby="comparison-title" onMouseDown={(event) => event.stopPropagation()}><div className="drawer-heading"><div><p className="eyebrow">Side by side</p><h2 id="comparison-title">Compare scenarios</h2></div><button className="icon-button" type="button" onClick={() => setComparisonOpen(false)} aria-label="Close comparison">×</button></div><div className="comparison-grid">{plan.scenarios.map((item) => { const selectedCourses = item.courses.filter((course) => course.status === "active"); const selectedUnits = selectedCourses.reduce((sum, course) => sum + course.units, 0); return <article key={item.id}><span>{item.id === plan.activeScenarioId ? "Current" : "Alternative"}</span><h3>{item.name}</h3><strong>{selectedUnits} units</strong><ul>{selectedCourses.map((planned) => <li key={planned.id}>{course(planned.courseId).code}<span>{planned.units}</span></li>)}</ul><button className="secondary-button" type="button" onClick={() => { setSelectedScenarioId(item.id); setComparisonOpen(false) }}>Open scenario</button></article> })}</div></section></div>}
    {agentHelpOpen && <div className="modal-backdrop" role="presentation" onMouseDown={() => setAgentHelpOpen(false)}><section className="agent-handoff" role="dialog" aria-modal="true" aria-labelledby="agent-handoff-title" onMouseDown={(event) => event.stopPropagation()}><div className="drawer-heading"><div><p className="eyebrow">WebMCP handoff</p><h2 id="agent-handoff-title">Refine with your agent</h2></div><button className="icon-button" type="button" onClick={() => setAgentHelpOpen(false)} aria-label="Close agent handoff">×</button></div><p>Ask a WebMCP-capable agent in your browser to inspect the current planning context, check this scenario, and propose one atomic edit.</p><blockquote>Review my Autumn plan. Preserve Fridays and my research block. Explain any tradeoffs, then make the smallest useful change.</blockquote><div className="agent-tool-note"><span>11</span><p><strong>Semantic tools available</strong><small>The agent can search context, inspect sources, check requirements, edit the plan, and return visible receipts.</small></p></div></section></div>}
    {reportOpen && <div className="modal-backdrop" role="presentation" onMouseDown={() => setReportOpen(false)}><section className="check-report" role="dialog" aria-modal="true" aria-labelledby="check-report-title" onMouseDown={(event) => event.stopPropagation()}><div className="drawer-heading"><div><p className="eyebrow">Deterministic validation</p><h2 id="check-report-title">Complete check report</h2></div><button className="icon-button" type="button" onClick={() => setReportOpen(false)} aria-label="Close check report">×</button></div><dl><div><dt>Units</dt><dd>{units} of {scenario.unitLimit}</dd></div><div><dt>Hard schedule conflicts</dt><dd>{checks.filter((item) => item.severity === "error").length}</dd></div><div><dt>Warnings and evidence gaps</dt><dd>{checks.filter((item) => item.severity !== "error").length}</dd></div><div><dt>Profile constraints checked</dt><dd>{workspace.profile.preferences.length + 3}</dd></div></dl>{checks.length === 0 ? <p className="report-clear">✓ All deterministic checks passed for this scenario.</p> : <ul>{checks.map((item) => <li key={item.id}><strong>{item.message}</strong><span>{item.suggestedRepairs[0]}</span></li>)}</ul>}</section></div>}
  </div>
}
